
export enum DigiteamFieldIdEnum {
    TICKET_ID = 'N#TICKET_ID',
    TICKET_REQUESTER_NAME = 'N#TICKET_REQUESTER_NAME',
    TICKET_NOTES = 'N#TICKET_NOTES',
    SERVICE_ADDRESS = 'N#SERVICE_ADDRESS',
    CRM_ACCOUNT = 'N#CRM_ACCOUNT',
    APPLICANT_NAME = 'N#APPLICANT_NAME',
    SERVICE_ADDRESS_CITY = 'N#SERVICE_ADDRESS_CITY',
    SERVICE_ADDRESS_STREET = 'N#SERVICE_ADDRESS_STREET',
    SERVICE_ADDRESS_STATE = 'N#SERVICE_ADDRESS_STATE',
    SERVICE_ADDRESS_COUNTRY = 'N#SERVICE_ADDRESS_COUNTRY',
    SERVICE_ADDRESS_LAT_LNG = 'N#SERVICE_ADDRESS_LAT_LNG',
    SERVICE_ADDRESS_NEIGHBORHOOD = 'N#SERVICE_ADDRESS_NEIGHBORHOOD',
    SERVICE_ADDRESS_POSTALCODE = 'N#SERVICE_ADDRESS_POSTALCODE',
    SERVICE_SLA = 'N#SERVICE_SLA',
}

export enum Constants {

    LANGUAGE_US = 'en',
    LANGUAGE_PT = 'pt',
    LANGUAGE_ES = 'es',
    LANGUAGE_DEFAULT = LANGUAGE_US,

    GOOGLE_GEOLOCATION_COUNTRY = 'country',
    GOOGLE_GEOLOCATION_STATE = 'administrative_area_level_1',
    GOOGLE_GEOLOCATION_CITY = 'administrative_area_level_2',
    GOOGLE_GEOLOCATION_STREET = 'sublocality_level_3',
    GOOGLE_GEOLOCATION_POSTAL_CODE = 'postal_code',
    GOOGLE_GEOLOCATION_NEIGHBORHOOD = 'sublocality_level_1',

    GEOLOCATION_SEPARATOR = ',',

    DIGITEAM_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss'
}
